apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-backstage-devops
  annotations:
    github.com/project-slug: susanta2022/service-backstage-devops
spec:
  type: other
  lifecycle: unknown
  owner: guests
