apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-backstage-devops
  annotations:
    github.com/project-slug: susanta2022/service-backstage-devops
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  dependsOn:
    - resource:default/artists-db
  providesApis:
    - artist-api
