site_name: 'Backstage'
site_description: 'Main documentation for Backstage features and platform APIs'
repo_url: https://github.com/susanta2022/dev-backstage-service.git
edit_uri: edit/master/docs

plugins:
  - techdocs-core

nav:
  - Overview:
      - What is Backstage?: 'overview/what-is-backstage.md'
  